<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>
</head>

<body>
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?= $acteur->getId(); ?></td>
                <td><?= $acteur->getNom(); ?></td>
                <td><?= $acteur->getPrenom(); ?></td>
            </tr>
        </tbody>
    </table>
</body>

</html>