<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prenom</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?= $acteur->getId(); ?></td>
            <td><?= $acteur->getNom(); ?></td>
            <td><?= $acteur->getPrenom(); ?></td>
        </tr>
    </tbody>
</table>
<a href="http://localhost:8000/?controller=acteur&task=list">Retour</a>