<h1>Acteur</h1>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($acteurs as $acteur) :  ?>
            <tr>
                <td><?= $acteur->getId(); ?></td>
                <td><?= $acteur->getNom(); ?></td>
                <td><?= $acteur->getPrenom(); ?></td>
                <td><a href="http://localhost:8000/?controller=acteur&task=detail&id=<?= $acteur->getId(); ?>">En savoir plus</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>